### ISSUE TITLE
Scale button having strange behavior

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [nezvers/Godot-GameTemplate#21]
**Describe the bug**
In the options menu, the scale button doesn't do scaling. It turns on full-screen and prevent me from turning it off.

**To Reproduce**
1. Go in the option menu
2. Click on the scaling button (+ or -)
3. Try turning off full-screen

**Expected behavior**
I guess it should do scaling and not locking full-screen.

**Godot's version**
 - I'm on v3.2.1.stable.fedora

If you need more details feel free to ask :).

Thank you.

**Comment by maujin111** [comment]
@Lyaaaaaaaaaaaaaaa Could you please provide screenshot of the three steps?

**Comment by nezvers** [comment]
I'll take a look!

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
@maujin111, I'm not sure it will help you but here are some screenshots:

**Option menu with nothing before clicking on scaling**
![Scale_1](https://user-images.githubusercontent.com/44974422/100984012-67c8d880-354a-11eb-97ed-c47d22e30545.png)

**Option menu after clicking on scaling**
![Scale_3](https://user-images.githubusercontent.com/44974422/100984237-bfffda80-354a-11eb-8a02-0f323648770b.png)

Once I clicked on scaling I couldn''t turn off full-screen anymore and scaling - didn't do anything (the + turns on full-screen once again)

**Comment by nezvers** [comment]
@Lyaaaaaaaaaaaaaaa can you test the same behavior in the original GameTemplate project, because it works as expected for me. The scale on max enables fullscreen and scaling down automatically disables fullscreen even if it was turned on by the fullscreen button.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
I will test the original GameTemplate and inform you about the result.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
@nezvers You are right. It works very well on the original. I guess the problem comes from my project resolution & parameters. Or the ui I designed. I still need to learn :)!

Thank you! (Great addon by the way. It is saving me soo much time).

**Comment by nezvers** [comment]
It should be just those 2 methods in SettingsResolution.gd:
set_scale() & set_fullscreen().

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
I updated the interface (to make it smaller) and better. Scaling '+' no longer lock my application in full screen and scaling '-' turns turns off the full screen.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Hello, I think you can close the issue as Godot-GameTemplate wasn't the source of the problem :)
