### ISSUE TITLE
Pause menu glitch

### ISSUE THREAD

**Issue by markim** [nezvers/Godot-GameTemplate#26]
Hello,

First, thank you to all of the contributors for this great template!

I noticed that when you join the game, if you click the "Go Back" button and quickly hit escape for the pause menu (before the scene switch happens), you  can end up in a weird state where you have the pause menu showing on the main menu:

![image](https://user-images.githubusercontent.com/1740400/112068055-5f5ed280-8b26-11eb-8e8b-eaa12b471f2c.png)

I found a quick fix and will create a MR off of this issue. #27

**Comment by nezvers** [comment]
Ahh, sorry for the late notice. I'll check it out and merge your pull request.

**Comment by markim** [comment]
Thanks for the update! No worries, it's a busy world we live in. After reviewing this one more time, I actually noticed one more small bug doing the same thing with the pause menu when you hit the main menu button and then hit pause again. I can make a PR. I think after that one, the pause menu glitch will be fully fixed.

Thanks again.
