### ISSUE TITLE
Font for cyrillic support

### ISSUE THREAD

**Issue by Th-eo** [nezvers/Godot-GameTemplate#28]
This is a very complete pixel font https://fontstruct.com/fontstructions/show/1765530/pixellocale-v-1-4

**Comment by markim** [comment]
I can do this-- I have a local project that fixed this from the template. I will make a PR soon.

**Comment by markim** [comment]
Added the Pixel Locale font and some other fixes / cleanups here: https://github.com/nezvers/Godot-GameTemplate/pull/29

**Comment by nezvers** [comment]
PR approved.
