### ISSUE TITLE
Control Menu doesn't accept InputEventMouseButton event

### ISSUE THREAD

**Issue by KometFox** [nezvers/Godot-GameTemplate#34]
While I used this template I just noticed that the script doesn't handle mouse buttons event at all which makes it impossible to configure the mouse buttons for things like firing or other key bindings I had to place `InputEventMouseButton` on several places which is popup.gd, SettingsControl.gd and Controls.gd to get the menu to accept mouse buttons.

**Comment by nezvers** [comment]
Ah yes. I haven't thought to use a mouse for this template. Good point.
