### ISSUE TITLE
FYI: Suggestion for possible basic word translation resource

### ISSUE THREAD

**Issue by follower** [nezvers/Godot-GameTemplate#7]
The Polyglot Gamedev project is a spreadsheet with translations (for multiple languages) for a range of basic words common in games: <https://docs.google.com/spreadsheets/d/17f0dQawb-s_Fd7DHgmVvJoEGDMH_yoSd8EYigrb0zmM/edit#gid=296134756>

It might be helpful for some basic translations in the template.

I discovered it via the itch.io developer game upload pages.

**Comment by nezvers** [comment]
Thanks, I'll check it out.
